export const FETCH_USER_DETAILS_REQUEST = "FETCH_USER_DETAILS_REQUEST";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";
export const FETCH_USER_REPOS_REQUEST = "FETCH_USER_REPOS_REQUEST";
export const FETCH_USER_REPOS_SUCCESS = "FETCH_USER_REPOS_SUCCESS";
export const FETCH_USER_REPOS_FAILURE = "FETCH_USER_REPOS_FAILURE";
